name: focus
main: ru.crazylegend.focus.Bootstrap
author: CrazyLegend_
version: 1.0

commands:
  focus:
    description: Display plugin information

permissions:
  focus.command.info:
    default: true